version: '3'

services:
  web:
    container_name: docSite
    build:
      context: .
      dockerfile: ./try2/try2/Dockerfile
    depends_on:
      - 'postgres'
    networks: 
      - superCoolNet
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - "./tables.sql:/docker-entrypoint-initdb.d/tables.sql"
    networks: 
      - superCoolNet


networks: 
  superCoolNet:
    driver: bridge


# new change